- hosts: webservers
  become: true

  tasks:
    - name: install httpd package
      yum:
        name: "{{package_name}}"
        state: latest
      tags: install
        - install

    - name: copy index.html file
      copy:
        src: index.html
        dest: /var/www/html/index.html
      tags: copy
        - copy
      notify:
        - start httpd server

  handlers:
    - name: start httpd server
      service:
        name: "{{package_name}}"
        state: started
